### ISSUE TITLE
Bintray Downloads don't Work for Versions 4.2 and 4.4

### ISSUE THREAD

**Issue by ScottHaney** [JFXtras/jfxtras-styles#13]
I used maven to download the jar from bintray and found that both versions 4.2 and 4.4 are invalid jar files. When I run `jar tf` on it there is an error. Also trying to unzip the jar using a generic zip program I get an error about the jar not being a valid zip file. If I use version 4.0 everything works fine.

**Comment by dukke** [comment]
Are you sure about this?

I've downloaded version 4.2 from bintray, extrated the jar using WinRAR and everything seems to be in order:

![issue - jmetro](https://user-images.githubusercontent.com/2707487/46538383-cc754380-c8ab-11e8-84e5-705987cd40dc.png)

**Comment by dukke** [comment]
I'll close this issue a week from now if there are no new developments from the reporter.

Thanks.

**Comment by dukke** [comment]
Closing this issue, like promised, as not an issue, since no new further comments were added to the issue.
