### ISSUE TITLE
Slider height taller than it needs to be

### ISSUE THREAD

**Issue by runiter** [JFXtras/jfxtras-styles#132]
When putting a Slider next to TextField I noticed that they don't seem to be aligned properly.
Then I changed the background color of Slider and noticed that it's because Slider height is taller than it needs to be:

![image](https://user-images.githubusercontent.com/3038088/69591334-750ac900-0fc0-11ea-9ba2-90bbc454b43a.png)

Note that the top of the slider is touching the top border but is there an empty space between the bottom of the slider and the bottom edge of the border.

**Comment by dukke** [comment]
Hi @runiter 
Can you attach a small test app that demonstrate the problem?

BTW does the problem also happen on the default javafx modena theme?

Thanks,

**Comment by runiter** [comment]
Hi @dukke 
Yes the problem happens in default javafx modena theme too.
But it's not as noticeable in modena because the controls there are generally smaller.

I will try to make a small test app soon.

**Comment by dukke** [comment]
@runiter I'm going to mark this issue as "not an issue" unless you have something else to add..

**Comment by dukke** [comment]
Since no further comments were added, closing this issue.
