### ISSUE TITLE
Maven: Cannot use JMetro styling

### ISSUE THREAD

**Issue by Colocasian** [JFXtras/jfxtras-styles#139]
Output of `java -version`:
> openjdk version "11.0.6" 2020-01-14
> OpenJDK Runtime Environment (build 11.0.6+10)
> OpenJDK 64-Bit Server VM (build 11.0.6+10, mixed mode)

Output of `mvn -v`:
> Apache Maven 3.6.3 (NON-CANONICAL_2019-11-27T20:26:29Z_root)
> Maven home: /opt/maven
> Java version: 11.0.6, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk
> Default locale: en_US, platform encoding: UTF-8
> OS name: "linux", version: "5.4.15-2-manjaro", arch: "amd64", family: "unix"

I tried using JMetro styling on my JavaFX project in Maven (made using archetype `javafx-archetype-simple` from `org.openjfx`), but whenever I tried to run my project using `mvn -s settings.xml javafx:run`, it specified that package was not found. Downloaded JMetro jar files from JCenter. Output of `mvn -s settings.xml javafx:run`:
> [INFO] Scanning for projects...
> [INFO]
> [INFO] ----------------< io.colocasian.calc:ore-no-calculator >----------------
> [INFO] Building ore-no-calculator 1.2-SNAPSHOT
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO]
> [INFO] >>> javafx-maven-plugin:0.0.4:run (default-cli) > process-classes @ ore-no-calculator >>>
> [INFO]
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ore-no-calculator ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] skip non existing resourceDirectory /home/rishvic/Documents/Java/ore-no-calculator/src/main/resources
> [INFO]
> [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ ore-no-calculator ---
> [WARNING] Can't extract module name from jmetro-11.6.5.pom: zip END header not found
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 3 source files to /home/rishvic/Documents/Java/ore-no-calculator/target/classes
> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR :
> [INFO] -------------------------------------------------------------
> [ERROR] /home/rishvic/Documents/Java/ore-no-calculator/src/main/java/io/colocasian/calc/App.java:[17,22] package jfxtras.styles does not exist
> [ERROR] /home/rishvic/Documents/Java/ore-no-calculator/src/main/java/io/colocasian/calc/App.java:[35,26] cannot find symbol
>   symbol:   class Style
>   location: class io.colocasian.calc.App
> [ERROR] /home/rishvic/Documents/Java/ore-no-calculator/src/main/java/io/colocasian/calc/App.java:[35,40] cannot find symbol
>   symbol:   variable Style
>   location: class io.colocasian.calc.App
> [ERROR] /home/rishvic/Documents/Java/ore-no-calculator/src/main/java/io/colocasian/calc/App.java:[377,13] cannot find symbol
>   symbol:   class JMetro
>   location: class io.colocasian.calc.App
> [INFO] 4 errors
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  1.443 s
> [INFO] Finished at: 2020-01-31T21:46:28+05:30
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project ore-no-calculator: Compilation failure: Compilation failure:
> [ERROR] /home/rishvic/Documents/Java/ore-no-calculator/src/main/java/io/colocasian/calc/App.java:[17,22] package jfxtras.styles does not exist
> [ERROR] /home/rishvic/Documents/Java/ore-no-calculator/src/main/java/io/colocasian/calc/App.java:[35,26] cannot find symbol
> [ERROR]   symbol:   class Style
> [ERROR]   location: class io.colocasian.calc.App
> [ERROR] /home/rishvic/Documents/Java/ore-no-calculator/src/main/java/io/colocasian/calc/App.java:[35,40] cannot find symbol
> [ERROR]   symbol:   variable Style
> [ERROR]   location: class io.colocasian.calc.App
> [ERROR] /home/rishvic/Documents/Java/ore-no-calculator/src/main/java/io/colocasian/calc/App.java:[377,13] cannot find symbol
> [ERROR]   symbol:   class JMetro
> [ERROR]   location: class io.colocasian.calc.App
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Gist containing `pom.xml`, `settings.xml` (for using JCenter), and the `App.java` file where I used the the `Style` and `JMetro` classes [here](https://gist.github.com/Colocasian/67da35c1a00ca802a0ffe919d62d1e3e). Really a noob regarding Maven, would really appreciate some advice.

**Comment by dukke** [comment]
Hi Rishvic,

Yeah, I might have forgotten to upload to Maven Central, I'll check that, thanks. However I'm sure JMetro exists in JCenter so you can try that.

About your Maven issues, unfortunately I'm not a Maven guy, I'm a Gradle guy. So I'm also a noob on that and can't help you out. 

These questions are also better answered elsewhere on Maven related forums or StackOverflow, since it's not an issue with JMetro (JMetro is available in JCenter).
With that in mind I'm going to mention @tbee here (depending on his availability) he might know Maven much better than me, however like I mentioned I think you'd be better off asking Maven questions on Maven forums or general purpose programming forums. 

Thanks :)

**Comment by Colocasian** [comment]
Thanks for the response :smile: . Then I'll close this issue here and then comment down the solution I find in the forums afterwards, just as a reference for others who may end up reading this thread.

**Comment by dukke** [comment]
OK thanks 👍

**Comment by LavishKothari** [comment]
It works if you pull this dependency from JCenter.
Add the JCenter repository as the first entry inside your `<repositories>` section:

```xml
<repository>
    <id>jcenter</id>
    <name>JCenter</name>
    <url>https://jcenter.bintray.com/</url>
</repository>
```
