### ISSUE TITLE
The New Fluent Design

### ISSUE THREAD

**Issue by Adorable-SkullMaster** [JFXtras/jfxtras-styles#14]
I love the what you've built. But is there a plan on rewriting JMetro for the new Fluent Design Guidelines?

**Comment by dukke** [comment]
Apologies for the late reply. Unfortunately due to a configuration issue I wasn't getting any notifications when new issues were entered in this project.

**Comment by dukke** [comment]
Thanks, I'm happy you like it.

JMetro is indeed now inspired by Fluent Design. That is stated in the documentation page.

Cheers,
