### ISSUE TITLE
Pane background hiding button borders

### ISSUE THREAD

**Issue by runiter** [JFXtras/jfxtras-styles#141]
I noticed that after I upgraded JMetro to the latest version, the button borders are no longer visible because the background color of Pane is essential same as Button colors:

The old JMetro:
![image](https://user-images.githubusercontent.com/3038088/73602969-76211f00-454a-11ea-98e7-4ab5d0309a0b.png)

The new JMetro:
![image](https://user-images.githubusercontent.com/3038088/73602972-86d19500-454a-11ea-8b81-6fe26558ce65.png)

Is this a bug or by design? If by design, what's the rational behind it?
Other Fluent Design apps that I worked with don't seem to have borderless button except in toolbars.

**Comment by dukke** [comment]
Hi Saeid,

Are the buttons inside a Toolbar? Do they have the "light" styleclass? If the answer is no to these questions then they should have borders (i.e. buttons should have a background).


Thanks.

**Comment by runiter** [comment]
No they are not inside a Toolbar and they do not have the "light" styleclass.
They are in a GridPane.
I guess this is a bug then.

Note that the button does have a background, but the default background color happen to be same as the default TabContent pane background color. If I override the background color of TabContent pane with css to a different color, then I can see the borders of buttons.

```
.tab-content-area {
    -fx-background-color: red;
}
```

![image](https://user-images.githubusercontent.com/3038088/73611477-2f661000-45b0-11ea-8033-fe8df0c61293.png)

By the way, what does the method JMetro.setAutomaticallyColorPanes() do?

**Comment by dukke** [comment]
Are you adding the "background" styleclass to the container of the buttons, in this case I would assume it would be the GridPane? And also on any container that's supposed to have a background color?

**Comment by runiter** [comment]
No I wasn't, but I just did it now and now I can see the borders:

![image](https://user-images.githubusercontent.com/3038088/73612843-7b6b8180-45bd-11ea-9f1b-dc854630bc83.png)

Do I need to add "background" styleclass to all panes that contain buttons manually?

**Comment by dukke** [comment]
No, not all Panes that contain buttons. To all Panes that are supposed to have a background color. Otherwise there is no way for JMetro to know which Panes are supposed to have a background color or not. 
Alternatively JMetro has the `automaticallyColorPanes` property that you can set to true and JMetro will assume all Panes are backgrounds and color them accordingly. However, I think the previously mentioned way is the preferred way, as in this last case JMetro might color some Panes as background which you don't want to be backgrounds.

I've been rewriting the whole documentation of JMetro in the JMetro page and am about to release it. I've added documentation about this which might have escaped some people that haven't read this in the blog posts I post from time to time.

**Comment by dukke** [comment]
@runiter Can I close this issue?

**Comment by runiter** [comment]
But I tried calling `setAutomaticallyColorPanes(true)` and that didn't help. Only setting styleclass to "background" helped.
Is that a bug?

**Comment by dukke** [comment]
It depends. The only way to know is if you attach a small self contained test app to this issue that I can test and debug and see what's happening. This property seems to be working in the samples that exist in the samples sub-project but maybe there's some corner case or maybe there's something in your app. I don't know, only with that small test app will I be able to know.

I'm not sure if I want to continue supporting the `automaticallyColorPanes` property or just remove it and have only the option of adding the background styleclass to Panes that you want to have the background color.

BTW, the background styleclass is needed because in the LIGHT style the background is a light color (closer to white) and in the DARK style the background is dark (close to black).

**Comment by dukke** [comment]
I hope you understand.

This is standard practice, on any open source project (including JavaFX). You need to attach a small self contained test app that I can check and see if there is any bug with JMetro.

Thanks,

**Comment by runiter** [comment]
Thanks in future I will try to provide self contained test apps.
This problem seem to be limited to TabPane and SplitePane.
But since you're considering removing `automaticallyColorPanes` I think we don't need to investigate it.
The `background` styleclass solution will do.
You can close this ticket.

**Comment by runiter** [comment]
Actually, hold on please.
It looks two different background colors are used throughout the library so maybe I need to write a self contained test after all.

Before I do so, is this a bug or by design:
![image](https://user-images.githubusercontent.com/3038088/73617474-12036700-45ed-11ea-8673-50f059b1fca4.png)

I have a VBox inside a ScrollPane. I set the styleclass of VBox to `background`. Looking at screenshot above it seems Scrollbar uses a different background color. Is this by design or should I make a self contained test app for you to debug?

**Comment by runiter** [comment]
I think I found the source of this bug.
In `dark_theme.css` you have:

```
.split-pane {
    background_color: #333;
    border_color: #252525;
}

```
The `background_color` value of #333 seems wrong. Most other panes seem to use global `background_color` which defaults to #252525 for dark_theme.

Is this a bug or did you intentionally mean to set the background color of splitepane to same color as button background?

Here is the self-contained code:

```
		VBox pane = new VBox();
		pane.getChildren().add(new Label("Hello"));
		pane.getChildren().add(new Button("Hello"));
		pane.getChildren().add(new Button("Hello"));
		SplitPane splitPane = new SplitPane(pane);

		Scene scene = new Scene(splitPane);
		stage.setScene(scene);
		new JMetro(scene, Style.DARK);
		stage.show();

```

**Comment by dukke** [comment]
Hi again Saeid,

Thanks for looking into this issue in more detail.

That was done on purpose, though I'm not entirely sure of whether a different color from the current one would be better or not.. I haven't seen many cases of apps in Dark Style with an empty SplitPane (or with its background showing)..

**Comment by runiter** [comment]
It appears that the background of SplitPane is always inherited by all its children. So even if SplitePane has a VBox as its child (see code above), the background of VBox will be same as the background of SplitePane.

I also noticed that called `setAutomaticallyColorPanes(true)` does not fix this.

So I propose to change the `background_color` of `.split-pane` to use `background_color` variable.

Or better yet just remove the `splite-pane` css code from `dark_theme.css` so the follow default code from `base.css` is automatically used:

```
.split-pane {
    -fx-background-color: background_color, background_color;
}
```

**Comment by runiter** [comment]
While you're at it, I have another suggestion.
I noticed that by default the background color of TitledPane is very dark now, almost pure black.
It wasn't like this before.

I noticed that 6 months ago you added this:

```
.titled-pane {
    text_color: white;

    title_background_color: #1f1f1f;
    title_background_hover_color: #4a4a4a;

    border_color: #494949;

    arrow_color: white;

    content_background_color: #111;
}
```

Is there a particular reason why you decided that `content_background_color` should be `#111`? Is this standard Fluent Design standard or a personal choice? I think it makes more sense that TitledPane background be same as other panes.

I did notice that `setAutomaticallyColorPanes(true)` corrects this problem.

**Comment by dukke** [comment]
Hi again Saeid,

Sorry for the delay in answering your remarks, been busy with my day time job. 

1 - Regarding SplitPane, do you have an existing app where this issue is visible? Could you post pictures of the full app, so we can see what would work best? If you can't post them publicly could you send them to me privately?

2 - Regarding TitledPane, thanks for the suggestion. 
Fluent Design doesn't have a titled pane. This is a new style only existing in JMetro. Could you also post some pictures of a complete app that might be using this?

Thanks,

**Comment by runiter** [comment]
Sure.
Here is the screenshot of my app using your Dark JMetro without any modification:

![image](https://user-images.githubusercontent.com/3038088/74121491-bd845c80-4b95-11ea-85a9-ae4bd758344e.png)

Here is the same app after I made the following css modification to make it look like better and make button borders visible:

.split-pane {
    background_color: #252525;
}

![image](https://user-images.githubusercontent.com/3038088/74121469-a3e31500-4b95-11ea-9b7f-bf5780563605.png)

**Comment by runiter** [comment]
A here is the screenshot of wrong TitledPane color:

![image](https://user-images.githubusercontent.com/3038088/74121619-3aafd180-4b96-11ea-846c-1d6edb12f1af.png)

To fix this problem I had to use `jMetro.setAutomaticallyColorPanes(true)` method.

**Comment by dukke** [comment]
Hi again Saeid,

Nice app you've got there. Perhaps when it's finished I could share it as an app that is using JMetro?

Regarding ScrollPane, can you check out latest release: 8.6.9-RC-03?

Thx

**Comment by dukke** [comment]
If you don't mind I'm going to separate this issue and file a new one regarding TitledPane so we can discuss there.

**Comment by saeidN** [comment]
Thanks Pedro, glad you like the app.
It only looks good thanks to your library :)
Yes you can certainly share it to promote JMetro capabilities.

I will try the latest release tonight and will report back.

**Comment by runiter** [comment]
Hi Pedro,
Can you provide me with link to jar file for 8.6.9-RC-03?
When I tried to acquire using maven it ended up download a different jar (controlsfx-8.40.14.jar)
I don't use maven much so could be my mistake. In any case I'm old school so a jar is much more useful for me.

**Comment by dukke** [comment]
Hi again Saeid,

I'm not a maven guy myself, I'm use gradle usually.

Try to use JCenter as the repository. Anyway if you want to download the jars, try to see if you can download from here: https://bintray.com/dukke/maven/jmetro.

There is already a new version: 8.6.9-RC-06.

**Comment by runiter** [comment]
Thanks Phil, I tried the new version and it works great :)
So the issue with split-pane is solved now and you can close this issue.

**Comment by dukke** [comment]
OK thx Saeid
