### ISSUE TITLE
TitledPane - Check background color of TitledPane

### ISSUE THREAD

**Issue by dukke** [JFXtras/jfxtras-styles#145]
Here's a screenshot of an app made by @runiter:

![74121647-6337cb80-4b96-11ea-8d3a-75d27747221f](https://user-images.githubusercontent.com/2707487/74385340-3b8d7100-4deb-11ea-9ed2-9b3149dee6a0.png)

Here's another but this time with the TitledPane with a different background (different from the current one in JMetro):

![74121518-d4c34a00-4b95-11ea-91f2-3398bf9050f9](https://user-images.githubusercontent.com/2707487/74385529-a63eac80-4deb-11ea-8581-399915aa5910.png)

Think about what would be the best background for the TitledPane.

**Comment by dukke** [comment]
I would still opt for the titledpane color of JMetro

**Comment by runiter** [comment]
But that's inconsistent with default Windows Fluent design, no?

**Comment by dukke** [comment]
Can you tell me exactly what controls are title panes in the picture? I should have defined that clearly when I created this issue.. not sure we're talking about the same thing..

**Comment by runiter** [comment]
This is the title pane:
![image](https://user-images.githubusercontent.com/3038088/211166060-5f906fbf-10b8-425b-81ea-96240122f0c0.png)

I expect to see the color of both areas shown with red arrow to be same color, but by default they're different colors.
