### ISSUE TITLE
Jmetro and tableviewFilter (controlsfx)

### ISSUE THREAD

**Issue by zeljkosh** [JFXtras/jfxtras-styles#15]
Hi, i am using your theme in my javafx test playground, and when i apply tablefilter from controlsfx on table, and try to right click on column name, i do get sorting options but i also get crash in application. i can copy paste error that i get , but its null pointer exception related to textfieldSkin. When i disable your theme and just try vanila javafx everything is ok.

**Comment by dukke** [comment]
Apologies for the late reply. Unfortunately due to a configuration issue I wasn't getting any notifications when new issues were entered in this project.

**Comment by zeljkosh** [comment]
so here is the link https://file.io/KDda9K you can download and try it in an instant.
i wrote a comment in code where you should pay attention.
and here is pastebin of the error itself, though i think its better if you just take a look at example.

https://pastebin.com/frbiPd4D

**Comment by dukke** [comment]
I've isolated this to being a ControlsFX problem, not a JMetro issue.

I've created a new bug in ControlsFX issue tracker for you: https://bitbucket.org/controlsfx/controlsfx/issues/881/tablefilter-doesnt-work-with-other-themes
With a new test case inspired by yours.
