### ISSUE TITLE
JMetro Alert  - Expandable content "Expand all" Label stay in dark when the style is dark 

### ISSUE THREAD

**Issue by ClementGre** [JFXtras/jfxtras-styles#157]
Hello,

Everythings is in the title, this image illustrate what i said :
![Annotation 2020-05-28 111738](https://user-images.githubusercontent.com/51322714/83123535-53a4aa00-a0d5-11ea-8177-d5b983f8e629.png)
(Generated on the JMetro-Samples 11.6.11)

PS: My language is set to French so is is possibly due to this since I have "Afficher les détails" and not "Show details" or "Expand all"

Thanks !

**Comment by dukke** [comment]
Yeah, I got it too with English language.

Thanks for the report,
