### ISSUE TITLE
Allow overriding defaults without the use of "!important"

### ISSUE THREAD

**Issue by runiter** [JFXtras/jfxtras-styles#163]
In Javafx8 JMetro I had the following css to remove the X button.
But this code no longer works in Javafx14. The X button still shows:

```
.text-field {
    -right-button-visible: false;
}
```

In order for it work I had to add "!important":

```
.text-field {
    -right-button-visible: false !important;
}
```

Even in Javafx8 JMetro I had to use "!important" for few things too. Such as:

```
.table-view .column-header {
    -fx-padding: 0 0 0 3 !important;
}
.table-view .label {
    -fx-padding: 8 0 8 0 !important;
}
```

I think the root of the problem is this:

```
scene.getStylesheets().add("mycss.css");
new JMetro(scene Style.DARK);

```

In JMetro constructor, the jmetro css files are added to the end of the stylesheets list so they get priority.
Can you insert jmetro stylesheets at the beginning of the list instead to resolve this issue?

**Comment by gumara-dev** [comment]
Hello @runiter

try this:

`JMetro jMetro = new JMetro(scene Style.DARK);
jMetro.getOverridingStylesheets().add("mycss.css");`

[https://www.pixelduke.com/2019/08/25/new-jmetro-javafx11-compatible-version/](More Information)

Stephan

**Comment by dukke** [comment]
Hi @runiter 

Google CSS Specificity (this is the same for JavaFX CSS and Web CSS). And also do what Stephan mentioned.

Unfortunately JMetro css isn't yet an user agent stylesheet like Modena (there is an issue for this).

You need to make sure your rules have a higher specificity than JMetro's or that they have an equal specificity but appear later by using the `getOverridingStylesheets()` method to add them (rules that have the same specificty but appear later, win),

Anyways this should all be down to this as JMetro doesn't change anything in the JavaFX CSS engine (there aren't even any hooks to do that unfortunately).

Let me know if that worked.

Cheers,

**Comment by dukke** [comment]
Also a good use case for `!important` is: if you need to use it to make your rule apply then it means you need to increase your rule specificity.

**Comment by dukke** [comment]
Hey @runiter if you don't mind I'm going to close this issue.

When you have any feedback feel free to comment. If this actually happens to be a JMetro issue then I can re-open it again.

Cheers,

**Comment by runiter** [comment]
Sorry for the later reply.
Yes it's okay to close this since I can just continue to use !important to get around it.

I can't use more specifity unless I used # ids. I think `.table-view .label` is as specific as it can get, no?

Also I prefer not to user `overridingstylesheets ` because I would like it to work with Modena too (the user has the option to switch back and forth between Modena and JMetro).

**Comment by dukke** [comment]
You can have much more specificity than that. Examples: add in more intermediate children between tableview and label, add more styleclasses, use direct child relation, etc.

Ok sounds fair on the overridingstylesheets though perhaps you could remove/add stylesheets dynamically? Anyway the overriding stylesheets just makes sure your custom stylesheets go after JMetro stylesheets though that just affects the order of styles (which in case of equal specificity make your custom stylesheets win)
