### ISSUE TITLE
ToggleSwitch  - thumbs moves out of control bounds

### ISSUE THREAD

**Issue by macster110** [JFXtras/jfxtras-styles#166]
The ToggleSwitch thumb moves out of the ToggleSwtich bounds. This appears to be an issue with the JMetro theme at is does occur when using Modena. 

A minimal example is attached. This is using OpenJDK 13, JavaFX 14 and JMetro 11.6.12

In JMetro the toggle thumb moves to the wrong position on resize and is placed in the wrong position in the HBox. 

![image](https://user-images.githubusercontent.com/21099776/86017862-db5b3c80-ba24-11ea-98cf-0d3069f83224.png)

When using Modena the ToggleSwitch thumb stays within the ToggleSwitch bounds and the ToggleSwitch is placed in the correct postion in the HBox. 

![image](https://user-images.githubusercontent.com/21099776/86018065-1e1d1480-ba25-11ea-9c8e-eff3fcee266a.png)

```
package com.jamdev.maven.aipam;

import java.io.IOException;

import org.controlsfx.control.ToggleSwitch;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
import jfxtras.styles.jmetro.JMetro;
import jfxtras.styles.jmetro.Style;

/**
 * Test the toggle switch using JMetro. This a minimla example of a bug 
 * where the toggle switch thumb moves outside the toggle switch bounds. 
 * @author Jamie Macaulay 
 *
 */
public class ToggleSwitchApp extends Application {


    public static void main(String[] args) {
        launch(args);
    }

	private ToggleSwitch showPromptsSwitch;
    
    @Override
    public void start(Stage primaryStage) throws IOException {

    	
        StackPane root = new StackPane();
   
		
		primaryStage.setTitle("Toggle Switch Bug");
		
		BorderPane borderPane = new BorderPane(); 
		//user options ot display all clips as features. 
  		showPromptsSwitch = new ToggleSwitch(); 
  		showPromptsSwitch.selectedProperty().addListener((obs, oldVal, newVal)->{
  			
  		});
//  		showPromptsSwitch.setMaxWidth(100);

  		Label label = new Label("Hello my toggle switch: Resize to see toggle bug");
  		label.getStyleClass().add("label-title2");
  		HBox hBox = new HBox(); 
  		hBox.setAlignment(Pos.CENTER_LEFT);
  		hBox.setSpacing(5);
  		hBox.getChildren().addAll(showPromptsSwitch, label); 
  		
  		borderPane.setCenter(hBox);
  		

        root.getChildren().add(borderPane);
        
        
//        root.getStylesheets().add(darkStyle);
        primaryStage.setScene(new Scene(root, 200, 80));
        
    	//apply JMetro theme
		new JMetro(Style.LIGHT).setScene(root.getScene());
        
        primaryStage.show();
    }

}
```

**Comment by dukke** [comment]
Hi Jamie,

Does this also happen in Java11?

**Comment by dukke** [comment]
Hey @macster110, just to let you know that I'll be working on this issue starting end of this week. Not totally sure if I'll have time this week but will definitely have time for it next week.

**Comment by macster110** [comment]
Hey, sorry I missed this. Do you still want me to test on Java 11?

**Comment by dukke** [comment]
Yes please, if you have time for that.

It probably will also be a problem in java 11, just wanted to make sure as I currently don't have the bandwidth (time) to support 3 versions. i.e. I'm currently supporting java 8 and 11 and wouldn't have time to support other versions.

I've still been busy lately. I'm counting on starting to look at JMetro issues next week or perhaps starting this Sunday/Saturday.

**Comment by macster110** [comment]
Ok, will give it a go but probably won't get to it until next week. Thanks again for the help on this.

**Comment by dukke** [comment]
@macster110 Hi Jamie, sorry for the time delay in solving this.

I remade the ToggleSwitch skin from scratch (didn't like what I did). I believe I've fixed both issues that you've reported. Can you check? 

Latest version is "11.6.14-RC-07", it's available through Bintray.

Thx.

**Comment by macster110** [comment]
Thanks very much. I'll give it a go!

**Comment by dukke** [comment]
Hey @macster110 any news on this?

If you can, would be great to know if this is fixed.

Meanwhile I'll close down this issue, we can re-open if you find that the problem still persists.

Thx!

**Comment by macster110** [comment]
Apologies for the delay in this. Thanks very much for the fix. It seems to work!

Thanks again. 

Before 
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/21099776/94543289-2403db00-024a-11eb-9944-51f9165dabd0.png">

After
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/21099776/94543389-4b5aa800-024a-11eb-8774-78185db123e6.png">

**Comment by dukke** [comment]
Great, thanks!
