### ISSUE TITLE
[Feature Request] Tornadofx/Kotlin bindings?

### ISSUE THREAD

**Issue by Username404-59** [JFXtras/jfxtras-styles#167]
Could that be a thing?
I really like the fluent/metro design so using this library directly with tornadofx would be really cool!

**Comment by dukke** [comment]
I'm not very acquainted with TornadoFX.

**Comment by sschuberth** [comment]
Unfortunately, both https://github.com/edvin/tornadofx and https://github.com/edvin/tornadofx2 seem to be pretty much dead anyway. But it would be so cool to have a Kotlin DSL for JMetro after all!
