### ISSUE TITLE
How to apply JMetro theme on the ColorPicker Dialog

### ISSUE THREAD

**Issue by ClementGre** [JFXtras/jfxtras-styles#179]
Hello,
I saw in the JMetro Theme Tester that it is possible to apply the JMetro Theme on the Custom Color Dialog of a ColorPicker, but I didn't find how...
I have applied the JMetro theme on my window/scene and on my ColorPicker but when I open the Custom Color dialog, the dialog still have the Modena style.
![image](https://user-images.githubusercontent.com/51322714/98873635-61a97580-243e-11eb-8e1e-258dde4c7092.png)

I explored the code of the Theme Tester but I found nothing.
Thank you,
\- Clément G.

**Comment by dukke** [comment]
HI Clement!

Have you checked out the DialogSample sample class, in the samples subproject? It's a sample that shows dialogs.

Basically if you initialize the owner of the dialog, it will have the same style as the owner. If not, you have to run the code of setting JMetro on a scene all over again but for the Dialog, since a Dialog without owner will have its own scene. 
This happens regardless of using JMetro or not (it's a JavaFX thing).

Cheers,

**Comment by ClementGre** [comment]
Hi,
I saw in the DialogSample that you can call initOwner on a Dialog and you can apply the theme with getDialogPane().getScene().
The thing is that I don't know how to get the custom color dialog Object from a ColorPicker Object. I just ask you since you did that in the ThemeTester.
I didn't found a method like initOwner() or getDialog() on the ColorPicker Object and setting the JMetro theme to the ColorPicker don't set it to the CustomColor Pane.

\- Clément G.

**Comment by dukke** [comment]
Hi again @ClementGre !

Were you able to solve your problem?

If you look at the sample app "ColorPickerThrowsRuntimeException" in the jmetro-samples subproject you'll see there is nothing special you need to do to have the ColorPicker dialog appear with the JMetro theme.

**Comment by ClementGre** [comment]
Hi dukke,

I'm very confused, I applied my theme on the root pane of my Stage, and not directly on the Stage, and this was the issue.
Sorry for this, it was all my fault.

By the way, I notes that when I change the theme of the owner stage (by re-calling new JMetro()), the theme of the ColorPicker stage don't change, and it stay in the theme it had when I opened it for the first time.
I dont know if you are able to solve this issue, but it is not very important, I guess I should replace the ColorPicker to update its style.

Anyway, thank you. I close this issue, and you can re-open it if you want to solve this little "bug".
\- Clement

**Comment by dukke** [comment]
Hey again,

What do you mean by changing the theme? Do you mean like setting a different Style (Dark or Light)? The way to do it is to change the properties on the existing JMetro instance (associated with the Scene or Parent), not create a new one.

Thx,

**Comment by ClementGre** [comment]
Hi,
By changing the theme, I mean changing from dark to light or from light to dark.
At the begging I was re-calling new JMetro each time, but even by changing it to keep only one instance and so call .setStyle() to change style, it don't work and the JMetro ColorPicker popup stage stays to the style it has when I opened it for the first time.

\- Clement

**Comment by dukke** [comment]
I just ran ThemeTester and indeed everything seems to work fine when you change from DARK to LIGHT Style or vice-versa, except for the ColorPicker which remains with the same initial Style.

Can you file an issue for this ColorPicker problem you've found: ColorPicker remaining with the initial Style?
