### ISSUE TITLE
MenuBar style bug in a BorderPane

### ISSUE THREAD

**Issue by Dansoftowner** [JFXtras/jfxtras-styles#181]
Hi!

First of all, I want to thank you for this awesome library. It's just awesome.

I am in a scenario when I don't want to apply the JMetro style to the whole scene/root, just to some parts of it. 
I have a border-pane which has a `MenuBar` at the top, and other elements in the center, bottom etc... I want to apply the JMetro style only to the top MenuBar.

Unfortunately, I've experienced a missbahaviour when I run the application:
![JmetroBug1](https://user-images.githubusercontent.com/49782833/102226585-d6ae1600-3ee8-11eb-9e40-360bd64bfd9c.gif)

The `MenuBar` doesn't have the right background color.

Also, I have a warning message:
```
dec. 15, 2020 3:09:25 DU. javafx.scene.CssStyleHelper calculateValue
WARNING: Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in module javafx.graphics@11.0.6 of loader 'platform')' while converting value for '-fx-background-color' from rule '*.menu-bar' in stylesheet jar:file:/C:/Users/judal/.gradle/caches/modules-2/files-2.1/org.jfxtras/jmetro/11.6.14/e7a760f00799966e257a4fae37ab13563f461af9/jmetro-11.6.14.jar!/jfxtras/styles/jmetro/dark_theme.css
```

But, if I apply it to the whole `BorderPane` it doesn't have bugs, but this is not what I want:
![image](https://user-images.githubusercontent.com/49782833/102227280-aadf6000-3ee9-11eb-9cb7-12a811e899e4.png)

I experienced similar buggy things when I apply the JMetro style to a GUI element  but not to the whole Scene/Root (for example a `TableView`'s rows doesn't have the right background color on mouse hover).

I wrote a simple demo application just for demonstration:
```java
public class Main extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        final MenuBar top = new MenuBar();
        top.getMenus().add(
                new Menu("File", null,
                        new MenuItem("We want to have JMetro style"),
                        new MenuItem("Item 2"),
                        new MenuItem("Item 3")
                )
        );

        final StackPane center = new StackPane(new Button("I don't want to have JMetro Style"));

        final BorderPane root = new BorderPane();
        root.setTop(top);
        root.setCenter(center);

        //we only want to add the JMetro style to the MenuBar, not to the whole BorderPane
        new JMetro(Style.DARK).setParent(top);
        //new JMetro(Style.DARK).setParent(root) -> it works, but it's not what I want

        primaryStage.setScene(new Scene(root));
        primaryStage.setTitle("Demo");
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```

I'm using Java 11.

Thanks for your help!

**Comment by dukke** [comment]
Hi @Dansoftowner 

Sorry for the late reply, I only had free time to look at this now.

This has been fixed in version "11.6.15-SNAPSHOT"

If you do check if the fix works for you, please let me know.

Thanks!
