### ISSUE TITLE
TextArea throwing warnings

### ISSUE THREAD

**Issue by akorynta** [JFXtras/jfxtras-styles#19]
When using a javafx.scene.control.TextArea in my application, I received the following warnings:

Nov 07, 2018 3:52:39 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve 'border' while resolving lookups for '-fx-background-color' from rule '*.text-input' in stylesheet jar:file:/C:/Users/adam/.m2/repository/org/jfxtras/jmetro/4.6/jmetro-4.6.jar!/jfxtras/styles/jmetro8/JMetroLightTheme.css
Nov 07, 2018 3:52:39 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve 'highlight' while resolving lookups for '-fx-highlight-fill' from rule '*.text-input' in stylesheet jar:file:/C:/Users/adam/.m2/repository/org/jfxtras/jmetro/4.6/jmetro-4.6.jar!/jfxtras/styles/jmetro8/JMetroLightTheme.css
Nov 07, 2018 3:52:39 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve 'highlight_text' while resolving lookups for '-fx-highlight-text-fill' from rule '*.text-input' in stylesheet jar:file:/C:/Users/adam/.m2/repository/org/jfxtras/jmetro/4.6/jmetro-4.6.jar!/jfxtras/styles/jmetro8/JMetroLightTheme.css
Nov 07, 2018 3:52:39 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve 'prompt_text' while resolving lookups for '-fx-prompt-text-fill' from rule '*.text-input' in stylesheet jar:file:/C:/Users/adam/.m2/repository/org/jfxtras/jmetro/4.6/jmetro-4.6.jar!/jfxtras/styles/jmetro8/JMetroLightTheme.css

I am using JDK 1.8_172 if that is helpful.

**Comment by dukke** [comment]
This has been fixed in 4.8.5 - https://github.com/JFXtras/jfxtras-styles/releases/tag/4.8.5
Thanks for reporting.

**Comment by akorynta** [comment]
Great! Fix worked perfectly, new TextArea themes look nice.

**Comment by dukke** [comment]
Thanks for confirming the fix is working.
