### ISSUE TITLE
DatePicker - Week number cell in DARK style has wrong background color

### ISSUE THREAD

**Issue by ENeMy235** [JFXtras/jfxtras-styles#190]
Hi, I just noticed, that when date picker is showing week number in dark style, there are white boxes instead of numbers.

Probably incorrect background in that cells?

Version: 11.6.14

![obrazek](https://user-images.githubusercontent.com/5091919/112825537-2a093600-908c-11eb-864a-fe3a5cc4638d.png)

**Comment by dukke** [comment]
Fixed. Currently available on version 11.6.15-SNAPSHOT
