### ISSUE TITLE
Slider - Unable to update slider by clicking on the track before the thumb

### ISSUE THREAD

**Issue by ClementGre** [JFXtras/jfxtras-styles#193]
To move the slider, you have to click after the slider.
It don't works to click before the slider, on the blue line:
![Slider issue example](https://user-images.githubusercontent.com/51322714/114480007-e0a60400-9bbe-11eb-9ebf-44b1441fbace.png)

So when you want to move the slider to the left, you can only grab the slider and drag it to the left.
This is not the case with the Modena style.

Thank you, Clement

**Comment by dukke** [comment]
Thanks for filing the issue Clement! :)

**Comment by dukke** [comment]
This might need to be solved later. I'm planning on having JMetro start using FXSkins library. All skins will be available in FXSkins so this needs to be solved there.

**Comment by dukke** [comment]
Hi @cansik @ClementGre 

Truly sorry for the late reply, I've been very busy with my work.

@cansik I've left a comment on the PR. Could you check it out?

Sorry again, cheers,
