### ISSUE TITLE
ColorPicker window remaining with the initial Style

### ISSUE THREAD

**Issue by ClementGre** [JFXtras/jfxtras-styles#194]
When you are switching the style of the stage of a ColorPicker (Dark to Light or vice-versa), the custom colour window of the colour picker is remaining to the JMetro style it has when it was open for the first time.

**Comment by dukke** [comment]
Thanks for filing this issue Clement!

**Comment by dukke** [comment]
This is a bug in JavaFX itself. 
I've filed an issue in the javafx issue tracker with my findings about this bug: https://bugs.openjdk.java.net/browse/JDK-8265339

Closing this as it's not a JMetro isssue.

Thanks,
