### ISSUE TITLE
Radio button dot is a square on WIn Xp

### ISSUE THREAD

**Issue by drenda** [JFXtras/jfxtras-styles#2]
Hi,
Jmetro style is very beautiful but the dot of an radio button in Win Xp sp3 is a square.
The image maybe can clarify.
![test](https://f.cloud.github.com/assets/3420646/108522/81a1500a-6a52-11e2-92db-d470ea042145.jpg)

Thanks

**Comment by dukke** [comment]
I also think that Windows XP isn't supported by JavaFX, you can tell me otherwise if that's the case..

Closing this issue..
