### ISSUE TITLE
Button, ToggleButton - Button does not show border on hover when it is focused

### ISSUE THREAD

**Issue by mpe85** [JFXtras/jfxtras-styles#206]
When a button is focused and the mouse is moved over it, the button border is not displayed.
With the toggle button, however, this works.

![2021_08_03_10_31_15_Window](https://user-images.githubusercontent.com/23398713/127984421-024f7b0f-4e96-489e-8c40-af57dccd234c.jpeg) Border is shown on hover if button is not focused
![2021_08_03_10_31_52_Window](https://user-images.githubusercontent.com/23398713/127984477-61e6b28f-004f-43fe-876a-d1b476c7a6af.jpeg) Border is not shown on hover if button is focused

I'd expect the border to be shown in both cases. Is this by design or is it a bug?
How can the button be configured so that the border is also shown when it is focused?

**Comment by dukke** [comment]
Good idea @mpe85 
This has been fixed and pushed.
