### ISSUE TITLE
Maven Central Repository Does Not Install Correctly

### ISSUE THREAD

**Issue by porl** [JFXtras/jfxtras-styles#207]
Hi there
When trying to add JMetro via Maven Central, everything seems to work but I do not seem to get access to the jxtras namespaced packages in my project. Manually downloading the jar from the releases here and adding it to my local maven repository works fine though.

For reference, I'm using intellij. Removing the .idea directory and reimporting the pom.xml project makes no difference - Maven Central version does not work but locally installed version is fine.

**Comment by dukke** [comment]
Searching through Maven Central, I can see JMetro 11.6.15 is there: https://search.maven.org/artifact/org.jfxtras/jmetro/11.6.15/pom

It might not have been previously by mistake but it is now since: 9 May 2021

I'll close this issue soon if there are no further comments..
