### ISSUE TITLE
TextFields - Non-Editable TextFields shouldn't have a 'clear' button

### ISSUE THREAD

**Issue by buko** [JFXtras/jfxtras-styles#209]
jmetro version: 11.6.15

The JMetro theme introduces an 'X' in TextField controls that provides a quick way to remove all text from a TextField. This functionality does not respect the editable property of a TextField. 

Even when a TextField is made non editable:

1) The 'X' symbol appears.
2) Clicking on the 'X' removes the text in the field rendering the application unusable. (User can no longer make forward progress because the text is gone but the field is not editable so nothing can be added back.)

Solution:

Ideally when a TextField is made non-editable the 'X' functionality should be disabled.

**Comment by TheRedSpy15** [comment]
I found the temporary solution is to set the textfield to disabled

**Comment by satsen** [comment]
@TheRedSpy15 It's a bad solution because disabled and uneditable are not the same. When disabled, it also makes the field gray and unselectable. I created a PR but it will probably take time for it to get merged so just use this CSS for now:

```css
TextField:readonly {
    -right-button-visible: false;
}
```
