### ISSUE TITLE
Exception "Failed to load skin 'impl.jfxtras.labs.internal.scene.control.skin.ListSpinnerCaspianSkin'"

### ISSUE THREAD

**Issue by ThomasDaheim** [JFXtras/jfxtras-styles#210]
See https://github.com/JFXtras/jfxtras/issues/124. Root cause is in jfxtras\styles\jmetro\base_other_libraries.css, Line 40:

```
.ListSpinner {
    -fx-skin: "impl.jfxtras.labs.internal.scene.control.skin.ListSpinnerCaspianSkin";
    -fx-background-color: #f0f0f0;
    -fx-background-insets: 0 0 0 0;
    -fx-background-radius: 0;
    -fx-padding: 0.266667em 0.233333em 0.25em 0.233333em;
    -fx-text-fill: #212121;
}
```

**Comment by dukke** [comment]
Hi @ThomasDaheim

Truly sorry for the late reply, I've been very busy with my work!

I've left a comment in the PR. Just one small change to do.

Thanks and sorry again..

**Comment by dukke** [comment]
Fixed.
