### ISSUE TITLE
DatePicker - changes height when focused 

### ISSUE THREAD

**Issue by gabrielfontana** [JFXtras/jfxtras-styles#215]
JMetro 11.6.15
Liberica JDK+FX 11.0.14.1+1, LTS
IDE: Apache NetBeans 13
OS: Windows 10 Pro 21H2 

https://user-images.githubusercontent.com/79165243/160727275-2285bd62-abb0-45a3-bd2b-73eddb66e314.mp4

**Comment by dukke** [comment]
Hi @gabrielfontana 

Please provide a small sample app where this problem happens.

Thanks!
