### ISSUE TITLE
Spurious classifier tags in dependencies in pom.xml

### ISSUE THREAD

**Issue by almostobvious** [JFXtras/jfxtras-styles#216]
Do we really need classifier tags in the pom? Asking because these statements create a problem with bundling on linux where dependency resolution includes javafx*-win jars which are not necessary to run on linux - and more - prevent apps from running due to a clash in jars/modules.

**Comment by satsen** [comment]
Not sure what you are talking about. My program which I build (with jlink) for windows, linux and mac has no problems with this.

**Comment by satsen** [comment]
Are you using Gradle or Maven? I am using Gradle, maybe that could be why I don't have a problem. Also, could your problem be  related to #207?

**Comment by dukke** [comment]
Closing this as the reporter didn't answer the questions addressed to them.
