### ISSUE TITLE
Some suggestions of Jmetro on Windows 11

### ISSUE THREAD

**Issue by Etern-34520** [JFXtras/jfxtras-styles#221]
Hi.Jmetro is very harmonious on Windows 10. It is also good on Windows 11, but it does not support the dark mode of Windows 11 (or does JavaFX not support it?): The title bar is still bright white (all other applications are normal). My suggestion is to add a rounded UI CSS. As for the title bar problem, I will try to solve it myself.

Attachment: I am a Chinese high school student. I am using Jmetro to beautify my JavaFX application. I am using a machine translator. Therefore, there may be some errors. Please forgive me for the inconvenience.
![image](https://user-images.githubusercontent.com/93083287/183294892-2e354d0d-296e-4882-a0fc-db49da5a3ddf.png)

**Comment by dukke** [comment]
Hi @Etern-34520 

Thanks, I'm glad you like JMetro.

JavaFX doesn't provide nice ways to style the title bar of a window unfortunately. The best way I see to fix this would be to create a component (probably separate from JMetro) that has a Window that adapts to the dark mode of Windows and paints its frame accordingly. Or better yet, for the JavaFX framework to provide that.
