### ISSUE TITLE
New windows ui (winui3) implement

### ISSUE THREAD

**Issue by Jack253-png** [JFXtras/jfxtras-styles#223]
This is a new design of windows ui.It is in "Windows 11" and I think it is beautiful.
![image](https://user-images.githubusercontent.com/83895170/210220426-037cc046-d873-407f-b4a9-53a7905dbb49.png)
Can this be implemented in JavaFX?

**Comment by dukke** [comment]
Hi,

Yes there are a few things from windows 11 that could be a good source of inspiration for JMetro going forward.
Yes, it can be implemented in JavaFX.
