### ISSUE TITLE
Not correctly behavior disabled menu-item color.

### ISSUE THREAD

**Issue by MairwunNx** [JFXtras/jfxtras-styles#24]
![image](https://user-images.githubusercontent.com/39625750/50378517-2aacf980-0645-11e9-8a99-d44faac5c7e2.png)

![image](https://user-images.githubusercontent.com/39625750/50378519-3b5d6f80-0645-11e9-8b75-f7fddd064a6e.png)

Dark and light theme for disabled menu-item not correctly. It must be fully disabled without changing background \ hover color and just it UX rules :)

Maybe i improve it, and i set it not-hovering and without changing background if menu-item disabled.

**JMetroBase.css**: (Added to end of file)

![image](https://user-images.githubusercontent.com/39625750/50378535-8e372700-0645-11e9-8099-24adf00b3177.png)

```
/* disabled */
.menu-item:disabled:hover,
.menu-item:disabled:focused,
.menu-item:disabled:pressed {
    -fx-background-color: background_color;
}
```

Result: (I hover on disabled menu-item, but it hard to see :D)

![image](https://user-images.githubusercontent.com/39625750/50378548-deae8480-0645-11e9-99f2-3ca74a255cdb.png)

![image](https://user-images.githubusercontent.com/39625750/50378551-eb32dd00-0645-11e9-9e8f-16640294a8fc.png)

**Comment by dukke** [comment]
You're right. This has been fixed.

I've changed your suggestion from:
`-fx-background-color: background-color;`

to:

`-fx-background-color:transparent;`

We don't have a `background-color` variable defined in `menu-item`. Also this way it will always work as expected whether you have a background_color variable defined or not.

Thanks once again!

**Comment by MairwunNx** [comment]
No problem @dukke , thanks for attention! ) 😊🙋
