### ISSUE TITLE
How compile or run demo project?

### ISSUE THREAD

**Issue by MairwunNx** [JFXtras/jfxtras-styles#32]
Hi again @dukke! I try to compile your lib, ok, lib is compiled, but i can't start samples, how i can run it?
Sorry, i never work with gradle, and maybe i stupid in it.

![image](https://user-images.githubusercontent.com/39625750/51762423-bef4fb00-20e0-11e9-9585-64dda75c0099.png)

![image](https://user-images.githubusercontent.com/39625750/51762441-c7e5cc80-20e0-11e9-9e8a-e84722d8a1f9.png)

![image](https://user-images.githubusercontent.com/39625750/51762464-da600600-20e0-11e9-8d41-bb3284565bf7.png)

**Comment by MairwunNx** [comment]
Just i want to test my changes, but i can't it do while demo not ability to run. Any fixes?

**Comment by dukke** [comment]
Check your email, for answer.
