### ISSUE TITLE
Date-picker not correct text color on lost focus.

### ISSUE THREAD

**Issue by MairwunNx** [JFXtras/jfxtras-styles#34]
### Describe the bug
> - Incorrect color change text of text-box in date-picker when happens lost focus.

### Steps to reproduce the behavior
> 1. Add date-picker to your scene.
> 2. Put data in date-picker text-box or just select date.
> 3. Cause lost focus of it object, or focus on other ui element.
> 4. Again focus on out added date-picked ui element.
> 5. Now see issue, and read great it text :D. 

### Materials
![datapickerissue](https://user-images.githubusercontent.com/39625750/51790819-32633f00-21ab-11e9-800c-09d1b51da6ac.gif)

### Environment information
> - JMetro version: [Source Based]
> - System: [Windows 10 1809 x64]
> - Java Runtime Environment: [1.8.0_171]

**Comment by dukke** [comment]
Thanks, good issue

**Comment by MairwunNx** [comment]
@dukke no problem!

**Comment by MairwunNx** [comment]
@dukke new bugs with date-picker:

Focus traversable button need to disable, because after pressing and lost hover, causes not great effect.
 
![image](https://user-images.githubusercontent.com/39625750/52076644-2b1fa500-25a0-11e9-8b8e-db66231954da.png)

![image](https://user-images.githubusercontent.com/39625750/52076701-4d192780-25a0-11e9-8e9d-356d8815db01.png)

And it :D 

![image](https://user-images.githubusercontent.com/39625750/52076672-3bd01b00-25a0-11e9-8a2e-091be0e9e550.png)

**Comment by dukke** [comment]
Ok thanks for reporting that.

Could you please, possibly, file another issue for that bug?

Regarding the issue itself I'm not quite understanding what's it about.

**Comment by dukke** [comment]
Hmm. I still don't understand the issue, sorry.

**Comment by MairwunNx** [comment]
@dukke i fixed issue with wrong font size in context-menu for date-picker - understand?)
> ### bug what need to fix:
###### fix wrong dark theme for `date-picker`
###### fix wrong size for `date-picker` with disabled `editable` prop
###### ~~fix wrong font size in `context menu` in `date-picker`~~
###### fix wrong color selecting `today day` and selected `new day`
###### fix wrong colors of selecting `days` and `day cells`

currently i try fix all problems with date-picker.

**Comment by dukke** [comment]
Oh yes, I see it now. Wrong text size of Date-Picker context menu. Nice 👍

**Comment by MairwunNx** [comment]
![image](https://user-images.githubusercontent.com/39625750/52177813-a61ed080-27d7-11e9-818a-ac51b1b33d59.png)

fixed different height when disabled `editable` prop.

**Comment by dukke** [comment]
What's this last issue you mention?

**Comment by MairwunNx** [comment]
@dukke 
fix wrong size for date-picker with disabled editable prop.
https://github.com/JFXtras/jfxtras-styles/issues/34#issuecomment-459978179
> What's this last issue you mention?

**Comment by dukke** [comment]
is that last issue the wrong font size of the context menu of Date Picker?

**Comment by MairwunNx** [comment]
@dukke not, wrong font size already fixed, i mean wrong size when disabled editable property :)

**Comment by dukke** [comment]
Sorry... still not sure. Maybe if you tell me the steps to reproduce?

**Comment by MairwunNx** [comment]
I already done and fix dark theme for date-picker, i think it fully done.

> Before:

![image](https://user-images.githubusercontent.com/39625750/52179616-bc378b80-27ed-11e9-9f27-38f4ddd94cd4.png)

![image](https://user-images.githubusercontent.com/39625750/52179621-c5c0f380-27ed-11e9-80c7-c791e2a7c4d8.png)

![image](https://user-images.githubusercontent.com/39625750/52179627-cc4f6b00-27ed-11e9-842b-0c832f978b23.png)

> After:

![image](https://user-images.githubusercontent.com/39625750/52179636-ea1cd000-27ed-11e9-89e7-b7d75da0d304.png)

![image](https://user-images.githubusercontent.com/39625750/52179639-f0ab4780-27ed-11e9-9058-24b145b7c2d3.png)

![image](https://user-images.githubusercontent.com/39625750/52179640-f7d25580-27ed-11e9-9aea-23a6dd5bccdd.png)

![image](https://user-images.githubusercontent.com/39625750/52179646-ff91fa00-27ed-11e9-8a39-8b76795bb7f4.png)

![image](https://user-images.githubusercontent.com/39625750/52179649-06207180-27ee-11e9-9731-6b44bca46de6.png)

![image](https://user-images.githubusercontent.com/39625750/52179660-11739d00-27ee-11e9-9efb-9d14dc4f69d0.png)

**Comment by dukke** [comment]
Make the calendar icon color also white when the DatePicker is not focused.

**Comment by MairwunNx** [comment]
@dukke I can't do that, this is a direct violation of UX, the user will think that he is focused on the element, when he is not focused on it, if you want, I can do it, but this is not correct

**Comment by dukke** [comment]
The Fluent Design implementation of the Date Picker with a dark style has the Calendar icon white when the calendar is not focused.

![image](https://user-images.githubusercontent.com/2707487/52180191-2430a680-27db-11e9-9950-68cca852d1ee.png)

If it is gray I think it is not totally obvious that you can interact with the calendar icon button.

**Comment by MairwunNx** [comment]
In fluent design it make as button with icon :), we have as text-field and combobox :)

needed gray because text-field can be focus-able, bbut if you need write, you can edit color before merging branch

**Comment by dukke** [comment]
Yes that's right.

I still think the gray color makes it feel somewhat like the button is disabled.
