### ISSUE TITLE
Add support for TreeTableView

### ISSUE THREAD

**Issue by hwaite** [JFXtras/jfxtras-styles#36]
TreeTableView appears unaffected by JMetro theme.

**Comment by MairwunNx** [comment]
@hwaite style for TreeTableView be created soon.

**Comment by MairwunNx** [comment]
@hwaite @dukke it good looks? Sorry, tree-table-view styles hard to understand, on currenlty work stage i have

![image](https://user-images.githubusercontent.com/39625750/51917799-6039c500-23f1-11e9-962d-69e75154a894.png)

**Comment by dukke** [comment]
Looking good.

Can you have them more inline with the current Table style?

**Comment by MairwunNx** [comment]
@dukke i not looks on Table, if you can, drop here screenshot of table or demo :), thanks.

**Comment by dukke** [comment]
https://pixelduke.com/java-javafx-theme-jmetro/#Table_View

Main thing is, I think, they should both look similar. 
We could even change the current table view if we find a way to make it look better and then also have the tree table view look similar to that.

Thanks Pavel

**Comment by MairwunNx** [comment]
![jmetrotableviewlight](https://user-images.githubusercontent.com/39625750/51932983-5e7ff980-2411-11e9-9316-2757a9462a42.gif)

![jmetrotableviewdark](https://user-images.githubusercontent.com/39625750/51932984-5e7ff980-2411-11e9-8541-f3add87187aa.gif)

I done work, i think it good result, please review it and if like it i do PR. @dukke @hwaite

**Comment by MairwunNx** [comment]
- [x] Left align header text so it aligns with content text?
- [x] Use the same arrow that's used in Table View to indicate that the column is sorted
- [x] Replace blue vertical line with a line with a neutral color (black/white/gray) when dragging columns around
- [x] Light theme: Use gray on row hover like you are using in the dark theme. But try with a lighter gray.
- [x] Light theme: try a lighter accent color for selected row by using the derive css function.
- [x] In the dark theme: use a darker accent color with the derive css function for the selected row.
- [x] Dark theme: try with a darker gray for row mouse hover 
- [x] Remove mouse hover change of color on rows that have no data

![jmetrotableviewdark](https://user-images.githubusercontent.com/39625750/51989224-a22d3e80-24b7-11e9-8d58-f02620e908fa.gif)

![jmetrotableviewlight](https://user-images.githubusercontent.com/39625750/51989305-d4d73700-24b7-11e9-8f93-b2ec48a560a4.gif)

Done! If you like it, then i do PR, I did everything I could, and I do your instructions as much as possible :)
See changes @hwaite @dukke

**Comment by dukke** [comment]
Good job Pavel, I think it looks really good! Especially the dark theme.

You might be right about the #333333 color, I don't know. I think it's a question of seeing the table view style along with other JMetro controls in a real app and see if it looks good.

Yes, please do a PR.

**Comment by dukke** [comment]
About deriving the accent color and following my suggestions on that: when you do the PR maybe I'll try the derive and we can analyse it further and see if we like it better. 
I do feel that perhaps lighter accent color for light theme and darker accent color for dark theme might be better but it's a question of actually experimenting and seeing how it looks.

Thanks 👍

**Comment by MairwunNx** [comment]
@dukke ok! :), thanks, i do PR, i understand you. 👍

**Comment by MairwunNx** [comment]
resolved in #37

**Comment by dukke** [comment]
Closing this issue as this is now available.
