### ISSUE TITLE
Add style for split-pane ui element.

### ISSUE THREAD

**Issue by MairwunNx** [JFXtras/jfxtras-styles#38]
![jmetrosplitpanelight fix](https://user-images.githubusercontent.com/39625750/52002642-9a7b9300-24d3-11e9-9e4d-076ae0e3edef.gif)

![jmetrosplitpanedark](https://user-images.githubusercontent.com/39625750/52002643-9a7b9300-24d3-11e9-86bd-47fbeb63608a.gif)

@dukke Consider the changes, if everything suits you - I make PR, I think it turned out beautifully :), and if you make background `#333333`, then in general chocolate :D

p.s all colors by windows explorer scrollbar. (you can self see it on latest windows 10 build)

**Comment by dukke** [comment]
Style for Split Pane has been added meanwhile.
