### ISSUE TITLE
How to change the color of hover button and the previous button in Rating Control 

### ISSUE THREAD

**Issue by olaLH** [JFXtras/jfxtras-styles#4]
hi 
i use RatingControl, but my problem is when hover on button, the button that is hover and its previous buttons should also change its color.
i mean if the mouse is hover on third star so should hover the first and second star without change the rating value.  can i do that using rating control?.
thanks

**Comment by dukke** [comment]
Rating control is currently a control from the ControlsFX project. Not this project. Please post that question on the ControlsFX adequate place.
