### ISSUE TITLE
menu-button style not exists for light and dark styles.

### ISSUE THREAD

**Issue by MairwunNx** [JFXtras/jfxtras-styles#43]
![image](https://user-images.githubusercontent.com/39625750/52054095-6ef8b700-256c-11e9-913b-904adc2358cb.png)

![image](https://user-images.githubusercontent.com/39625750/52054111-77e98880-256c-11e9-813f-41981b923f79.png)

I already done style for menu-button, please see screenshots, it as button.
If you need menu-button style i can do PR. 👍 @dukke 

![image](https://user-images.githubusercontent.com/39625750/52054176-b0896200-256c-11e9-9273-bfa4ca1d9089.png)

![image](https://user-images.githubusercontent.com/39625750/52054193-be3ee780-256c-11e9-9f02-554f9b41d5b2.png)

**Comment by MairwunNx** [comment]
Hi @dukke , i fully understand you, you right, text align not cool and arrow too.

![image](https://user-images.githubusercontent.com/39625750/52070830-cc9ffa00-2592-11e9-8fa6-e41a060a82e4.png)

![image](https://user-images.githubusercontent.com/39625750/52070851-d6296200-2592-11e9-91e6-3ccd713c8113.png)

I think it edits better, see please :)

**Comment by dukke** [comment]
I personally feel the top one is better. 
We also need to be careful about the amount of size buttons and other controls have per default. We don't want them to be too big in a desktop app. 
Bigger means less things can fit on the screen and in a desktop, productivity app that's usually not very good.

On the other side on a mobile/tablet app we need controls to be big enough to be easily touched with the fingers. Since JavaFX target is mainly desktop apps we can stick with controls that are not too big.

**Comment by MairwunNx** [comment]
@dukke thanks! Button size like on bottom screen i set self, and other man can it do :D, because needed adaptation for sizes, on bottom screen i show with resized buttons, user self choose menu button size :))

If you like it, i can do PR with it changes. 👍

**Comment by dukke** [comment]
Sorry, can you say that again, didn't understand what you mean.

**Comment by MairwunNx** [comment]
@dukke i mean what user can self set button sizes, and need adaptation, because i and make bottom screenshot with demo on another button sizes.

**Comment by dukke** [comment]
I think the top one is better, personally. 

You can have a look at DropDownButton in Fluent Design.

**Comment by dukke** [comment]
Yes please, that would be awesome!

Thanks for your contributions. You've been doing a great job 👍

**Comment by dukke** [comment]
I'm sorry I haven't had time to answer more quickly, your PRs, hopefully I will have time during the weekend.

**Comment by MairwunNx** [comment]
thanks, JMetro good lib, and i it use, because i want to do JMetro better. 👍 

resolved in #44 

Left: `date-time-picker` fixes and `dialogs`.

**Comment by dukke** [comment]
This has been added. Thanks Pavel (@MairwunNx )
