### ISSUE TITLE
What's the stance on styling TableView with JMetro?

### ISSUE THREAD

**Issue by thomasnield** [JFXtras/jfxtras-styles#5]
Love the work being done with JMetro. It's a bummer it does not seem to work with TableView. It would be nice if that could be supported and look like the native XAML W8 table control like as shown below 
https://blogs.telerik.com/images/default-source/jesseliberty/image_thumb10022D9F8D8B6.png

**Comment by dukke** [comment]
Thanks!

I'll see if I can have a look at this in the next coming months.. depending on free time, sorry for the delay..

**Comment by dukke** [comment]
Look at https://pixelduke.com/2018/07/02/metro-table-for-java-javafx/ at tell me what you think.. meanwhile I'm closing this as the style was added and this is an old issue. Feel free to comment, criticize, etc even if the issue is closed, I can open it again if that's the case.

**Comment by thomasnield** [comment]
Wow I completely forgot about this, that looks really good :+1: Thank you.
