### ISSUE TITLE
demo application

### ISSUE THREAD

**Issue by MairwunNx** [JFXtras/jfxtras-styles#50]
It needed for any users of JMetro library, currently i do it.

**Comment by dukke** [comment]
Yes this is a good idea. I had thought about it before.

We can adapt this or maybe even use it as is:
- http://fxexperience.com/2013/01/modena-new-theme-for-javafx-8/ (read and check topic "Modena Test Application")
- The source code: http://hg.openjdk.java.net/openjfx/8u/rt/file/1942db1e52a9/apps/samples/Modena

**Comment by dukke** [comment]
.. or were you thinking of a real use case like app?

Thanks @MairwunNx , cheers,

**Comment by MairwunNx** [comment]
Resolved in https://github.com/JFXtras/jfxtras-styles/pull/35#issuecomment-472971004
