### ISSUE TITLE
License

### ISSUE THREAD

**Issue by julianseeger** [JFXtras/jfxtras-styles#6]
http://jfxtras.org/ states that 
> JFXtras and JFXtras Labs are licensed under the New BSD License

but this repository is missing any license information and it is unclear if it's part of "JFXtras and JFXtras Labs". Could you please add a license to this repo or at least confirm that any content here is licensed under the New BSD License?

**Comment by daviddbal** [comment]
Yes, the software is under the New BSD License.  This is my first contribution.   Does the new BSD header need to be on top of every source file?

**Comment by tbee** [comment]
Styles was contributed some time back by Pedro Vieira, a lot of the files are 2 years old or older, but he is committing actively again lately. All of JFXtras is under de New BSD license, we made sure it is in the  main and labs releases, but this repo needs some TLC there. You are right.

**Comment by tbee** [comment]
Added the license info to the readme.md of all repos
