### ISSUE TITLE
Size & font mismatch among different controls

### ISSUE THREAD

**Issue by runiter** [JFXtras/jfxtras-styles#62]
I noticed the following mismatch:

1. **Size:** Different controls seem to have different default sizes (see different height of Button vs ChoiceBox).

2. **Font:** Different controls seem to have different default fonts (see the size and color of Label vs Checkbox vs ChoiceBox).

3. **Background Color:** Some panes have back color in DARK mode, but not all (see the black TitlePane vs. white HBox).

Maybe some of these mismatch are intentional. If so, an explanation would be useful.

![ui](https://user-images.githubusercontent.com/3038088/56101927-bf8a7a00-5ef6-11e9-88b6-30316ff108e9.png)

**Comment by MairwunNx** [comment]
@runiter Hi! Thanks for report, i already complete background color for all controls in #39 
On fonts: I am aware of this problem, and I will correct it this week.

I have tables with font sizes from Fluent Design Language official documentation, and I also saw inconsistencies. This will be fixed.

**Comment by saeidN** [comment]
@MairwunNx fantastic! Thank you.
Do you have a link to the Fluent Design font size table that you can share here?

**Comment by runiter** [comment]
@MairwunNx fantastic! Thank you.
Do you have a link to the Fluent Design font size table that you can share here?

**Comment by MairwunNx** [comment]
@runiter sure! If you need more details, I will try to search :)

![image](https://user-images.githubusercontent.com/39625750/56133139-696c1400-5f94-11e9-98a6-f23f4b687628.png)
![image](https://user-images.githubusercontent.com/39625750/56133170-78eb5d00-5f94-11e9-901d-1a6971367c4c.png)

**Comment by saeidN** [comment]
@MairwunNx neat! Thank you.
I see that Body text uses font size 15px in Fluent Design. Is this the font size that should be the default for all Labels, Buttons, TextFields, ChoiceBoxes, and CheckBoxes? Or does Fluent Design apply different font size to different control types?

**Comment by MairwunNx** [comment]
@runiter i see UWP controls sizes:

TextBox (14px = Body but 14px).
![image](https://user-images.githubusercontent.com/39625750/56136783-1bf3a500-5f9c-11e9-993d-697eaebf13b2.png)

CheckBox (14px = Body but 14px)
![image](https://user-images.githubusercontent.com/39625750/56136826-39287380-5f9c-11e9-87f9-d2e76278f73c.png)

Button (14px = Body but 14px)
![image](https://user-images.githubusercontent.com/39625750/56136908-607f4080-5f9c-11e9-986c-66f59b9dcb5e.png)

ComboBox (14px = Body but 14px)
![image](https://user-images.githubusercontent.com/39625750/56136983-873d7700-5f9c-11e9-8a8d-b27c9bfd31c2.png)

RadioButton (14px = Body but 14px)
![image](https://user-images.githubusercontent.com/39625750/56137034-a1775500-5f9c-11e9-9da4-b75e97ae78c6.png)

Idk why in official documentation 15px, but in official SDK controls 14, i think it mistake, but better use 14px, as on screenshots.

**Comment by saeidN** [comment]
I'm cool with 14px.
Also glad to hear that all controls have same font size :)

**Comment by runiter** [comment]
I'm cool with 14px.
Also glad to hear that all controls have same font size :)

**Comment by MairwunNx** [comment]
@runiter @saeidN no problem 😊

**Comment by MairwunNx** [comment]
If problem resolved, close issue please. @runiter

**Comment by runiter** [comment]
Sorry for the confusion with 2 accounts. "runiter" is my main account :)

**Comment by MairwunNx** [comment]
No problem, i understand @runiter :)

**Comment by runiter** [comment]
Sure thing @MairwunNx . I'm closing it and will await the new version with all the fixes and improvements.

**Comment by dukke** [comment]
Hi @runiter, 

Could you please file an issue about the mismatch in font sizes in different controls and another one regarding different controls having different sizes (2 issues).

As Pavel said, we're already working on changing the background color of controls so no need to file that one.

Thanks.

**Comment by runiter** [comment]
@dukke sure thing.

**Comment by dukke** [comment]
Thanks
