### ISSUE TITLE
Programmatically filled password fields not masked

### ISSUE THREAD

**Issue by Schaezard** [JFXtras/jfxtras-styles#66]
When you create a new PasswordField object and fill it programmatically the password field is not masked, instead it shows the raw text.
The text is only masked after clicking the show password button once and then releasing it.
![image](https://user-images.githubusercontent.com/23404767/57289366-84293880-70bb-11e9-87c4-5e97eac5aad0.png)

**Comment by dukke** [comment]
This has been fixed on release version 5.4. 
Please test and provide feedback
Release notes:  https://github.com/JFXtras/jfxtras-styles/releases/tag/5.4

Thanks,

**Comment by Schaezard** [comment]
Tested and works, thanks.
