### ISSUE TITLE
TableView and Dialogs not working perfectly

### ISSUE THREAD

**Issue by ozordep** [JFXtras/jfxtras-styles#69]
Hi, it's more kind a doubt than a issue, i'm sorry if i'm posting this in the wrong place, but i need a little help. I have a project in JavaFX wich i'm using your fantastic lib, but i only import the JAR to the program. And there's a lot of things that are being missed, cause now i realized that i have to use a stylesheet. The problem is, i'm starting coding and i don't know what i have to download to make the styleesheet work, so if you can tell me i'll be so so glad. Thanks and sorry for my bad english.

**Comment by dukke** [comment]
Hi,

Check out this sample: https://github.com/JFXtras/jfxtras-styles/blob/master/samples/src/main/java/jfxtras/styles/jmetro/ControlsSample.java
and the JMetro documentation: https://www.pixelduke.com/java-javafx-theme-jmetro/, namely the "How to use" section.

Thanks.
