### ISSUE TITLE
Tabs?

### ISSUE THREAD

**Issue by vegancoder30** [JFXtras/jfxtras-styles#7]
I'm using this theme to make my B4J apps look prettier and so far it's awesome. However, I have noticed that the TabPane still has the Modena style.

What are the chances that you'll at least make the Tabs look Metro-ish?

**Comment by tbee** [comment]
Any chance you're going to pick this up, Pedro?

**Comment by dukke** [comment]
I didn't get this message, only seen it now because I checked Github. Github was set with an email I don't use.

I may be able to have a look at this in the following days..

Thanks,

**Comment by dukke** [comment]
This has been done: https://pixelduke.com/2018/07/15/jmetro-tab-treeview-contextmenu-java/
