### ISSUE TITLE
Licence problem

### ISSUE THREAD

**Issue by itday** [JFXtras/jfxtras-styles#8]
I only wanna to use your great "ToggleSwitch"-class (and necessary files to use this switch control) in a small JavaFX project with some settings. 

Therefore I looked up your licence definition. Your refer to an article which is generally about BSD licences. On this page I cannot recognice if you mean with "new" the 4-clause , the 3-clause or the 2-clause BSD licence?

Please help me in this lincene problem. I would appreciate using your software.

**Comment by tbee** [comment]
And there is a big difference for you depending on which BSD license is used?

**Comment by tbee** [comment]
JFXtras uses the 3-clause version.

**Comment by dukke** [comment]
As far as I know there is no ToggleSwitch class in jfxtras..
The only ToggleSwitch I know of, is my ToggleSwitch in ControlsFX..

**Comment by dukke** [comment]
Look for the ToggleSwitch in ControlsFX
