### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by aalmiray** [JFXtras/jfxtras-styles#9]
It would be great if the project would publish artifacts to Maven Central. I'm a big fan of Bintray however JCenter is not accessible at my current location (filtered by IT staff) and only Maven Central is allowed.

I can help setup the required bits in terms of Gradle configuration however the last step (Sonatype username & password) must behandled by @dukke.

**Comment by dukke** [comment]
Yep, that would be awesome! 

Maven Central seems to be the most used?

If you would setup the gradle configuration that would be great. Thanks!

**Comment by dukke** [comment]
It might also be possible to send the artifacts to maven central through the bintray web site. Not sure though..

**Comment by tbee** [comment]
From what I have heard that seems to be the case. The alternative solution is to make styles a subproject of JFXtras, and then it will be released to Maven central as part of a JFXtras release.

**Comment by dukke** [comment]
@aalmiray I missed your PR, sorry. I'll look into it tomorrow. Thanks!

**Comment by dukke** [comment]
I will try to have it done as soon as possible, I'll try to have this till the end of the weekend (till 29th July).

**Comment by dukke** [comment]
This has already been fixed for a while. Forgot to close this issue. JMetro is already present in Maven Central. Thanks @aalmiray for your help.
