### ISSUE TITLE
JMetro and ControlFX SpreadsheetView Headers 

### ISSUE THREAD

**Issue by Patowhiz** [JFXtras/jfxtras-styles#96]
I'm using JMetro to theme my application which uses [Control FX](http://fxexperience.com/controlsfx/features/) controls. I get a problem when I apply the theme to the [SpreadSheetView](http://fxexperience.com/controlsfx/features/) Control.. The spreadsheet control shrinks the column header when I click on any row. The screenshots below show this. How can I override the JMetro style classes used that affect this control? 

Before the click
![1](https://user-images.githubusercontent.com/21179007/62480696-62e0f280-b765-11e9-9640-946f5baa51a7.PNG)

After the click
![2](https://user-images.githubusercontent.com/21179007/62480709-6bd1c400-b765-11e9-9c3b-e11d32f0d86a.PNG)

**Comment by dukke** [comment]
Hi @Patowhiz !

You have to look at how javafx css works. JMetro doesn't change any of the underlying mechanisms of JavaFX css.

In a few words: you need to add your own stylesheet, setting styles for controlsfx spreadsheet control itself. Make sure your styles are more specific than the styles defined by JMetro (although JMetro doesn't define any style for spreadsheet it could have defined styles for other controls that spreadsheet ends up using, like tableview) or are as specific but come up being defined after JMetro.

Thanks,

**Comment by Patowhiz** [comment]
Thank you.
